# Generated by Django 5.0.3 on 2024-04-12 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Magazzino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("localita", models.CharField(max_length=3, unique=True)),
            ],
            options={
                "verbose_name": "Magazzino",
                "verbose_name_plural": "Magazzini",
            },
        ),
        migrations.CreateModel(
            name="Materiale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(max_length=20, null=True, unique=True)),
                ("descrizione", models.CharField(max_length=50)),
                ("unita_misura", models.CharField(default="PZ", max_length=5)),
                ("sottoscorta", models.IntegerField()),
                ("giacenza", models.IntegerField(default=0)),
                (
                    "creatore",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Materiale",
                "verbose_name_plural": "Materiali",
            },
        ),
        migrations.CreateModel(
            name="MaterialeMagazzino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("giacenza", models.IntegerField(default=0)),
                (
                    "magazzino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_magazzino",
                        to="catalog.magazzino",
                    ),
                ),
                (
                    "materiale",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_materiale",
                        to="catalog.materiale",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="materiale",
            name="magazzini_giacenza",
            field=models.ManyToManyField(
                blank=True, through="catalog.MaterialeMagazzino", to="catalog.magazzino"
            ),
        ),
        migrations.CreateModel(
            name="Movimenti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantita", models.IntegerField()),
                (
                    "data_movimento",
                    models.DateTimeField(auto_now_add=True, unique=True),
                ),
                (
                    "creatore",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "magazzino",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="magazzini",
                        to="catalog.magazzino",
                    ),
                ),
                (
                    "materiale",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimenti",
                        to="catalog.materiale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento",
                "verbose_name_plural": "Movimenti",
            },
        ),
    ]
