# Generated by Django 5.0.3 on 2024-04-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="magazzino",
            name="descrizione",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
