# Generated by Django 5.0.3 on 2024-04-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_magazzino_descrizione"),
    ]

    operations = [
        migrations.AddField(
            model_name="materiale",
            name="articolo",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="materiale",
            name="taglia",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="materiale",
            name="codice",
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
    ]
