# Generated by Django 5.0.3 on 2024-04-10 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_materiale_magazzini_giacenza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialemagazzino',
            name='movimenti',
        ),
        migrations.RemoveField(
            model_name='movimenti',
            name='magazzini_giacenza',
        ),
        migrations.AddField(
            model_name='materiale',
            name='magazzini_giacenza',
            field=models.ManyToManyField(blank=True, through='catalog.MaterialeMagazzino', to='catalog.magazzino'),
        ),
        migrations.AddField(
            model_name='materialemagazzino',
            name='materiale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_materiale', to='catalog.materiale'),
        ),
        migrations.AlterField(
            model_name='materialemagazzino',
            name='giacenza',
            field=models.IntegerField(),
        ),
    ]
