# Generated by Django 4.2.11 on 2024-03-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_movimenti_data_movimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimenti',
            name='materiale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.materiale'),
        ),
    ]
