# Generated by Django 5.0.3 on 2024-04-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_materialemagazzino_movimenti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiale',
            name='codice',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='materialemagazzino',
            name='giacenza',
            field=models.IntegerField(default=0),
        ),
    ]
