# Generated by Django 4.2.11 on 2024-03-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_movimenti_materiale'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimenti',
            name='data_movimento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='materiale',
            name='descrizione',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='materiale',
            name='sottoscorta',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='materiale',
            name='unita_misura',
            field=models.CharField(max_length=5),
        ),
    ]
