# Generated by Django 4.2.11 on 2024-03-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_movimenti_data_movimento_alter_materiale_descrizione_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiale',
            options={'verbose_name': 'Materiale', 'verbose_name_plural': 'Materiali'},
        ),
        migrations.AlterModelOptions(
            name='movimenti',
            options={'verbose_name': 'Movimento', 'verbose_name_plural': 'Movimenti'},
        ),
        migrations.AlterField(
            model_name='materiale',
            name='descrizione',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='movimenti',
            name='data_movimento',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimenti',
            name='magazzino',
            field=models.CharField(choices=[('NAP', 'Napoli'), ('MIL', 'Milano')], max_length=3),
        ),
        migrations.AlterField(
            model_name='movimenti',
            name='materiale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='movimenti', to='catalog.materiale'),
        ),
    ]
