# Generated by Django 5.0.3 on 2024-04-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_materiale_codice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiale',
            name='articolo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materiale',
            name='taglia',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='materiale',
            name='codice',
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
    ]
