# Generated by Django 5.0.3 on 2024-04-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_materiale_creatore_movimenti_creatore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materiale",
            name="sottoscorta",
            field=models.IntegerField(),
        ),
    ]
