# Generated by Django 5.0.3 on 2024-04-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_materiale_creatore_movimenti_creatore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiale',
            name='sottoscorta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='materiale',
            name='unita_misura',
            field=models.CharField(default='PZ', max_length=5),
        ),
        migrations.AlterField(
            model_name='movimenti',
            name='data_movimento',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
    ]
