# Generated by Django 5.0.3 on 2024-04-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_materiale_sottoscorta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiale',
            name='giacenza',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiale',
            name='descrizione',
            field=models.CharField(max_length=50),
        ),
    ]
