# Generated by Django 5.0.3 on 2024-04-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_materiale_giacenza_alter_materiale_descrizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiale',
            name='codice',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
