# Generated by Django 5.0.3 on 2024-04-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_materiale_codice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiale',
            name='giacenza',
            field=models.IntegerField(default=0),
        ),
    ]
