# Generated by Django 5.0.3 on 2024-04-09 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_materiale_giacenza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimenti',
            name='materiale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimenti', to='catalog.materiale'),
        ),
    ]
