# Generated by Django 5.0.3 on 2024-04-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_materiale_sottoscorta"),
        ("catalog", "0011_alter_materiale_giacenza"),
    ]

    operations = []
